---
apiVersion: kuadrant.io/v1beta2
kind: AuthPolicy
metadata:
  name: ${GATEWAY_NAME}-auth
  namespace: ${GATEWAY_NS}
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: ${GATEWAY_NAME}
  defaults:
    rules:
      authorization:
        "deny":
          opa:
            rego: "allow = false"
