---
apiVersion: kuadrant.io/v1alpha1
kind: TLSPolicy
metadata:
  name: ${GATEWAY_NAME}-tls
  namespace: ${GATEWAY_NS}
spec:
  targetRef:
    name: ${GATEWAY_NAME}
    group: gateway.networking.k8s.io
    kind: Gateway
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: ${CLUSTER_ISSUER_NAME}
