---
apiVersion: kuadrant.io/v1alpha1
kind: DNSPolicy
metadata:
  name: ${GATEWAY_NAME}-dnspolicy
  namespace: ${GATEWAY_NS}
spec:
  routingStrategy: loadbalanced
  loadBalancing:
    geo: 
      defaultGeo: US 
    weighted:
      defaultWeight: 120 
  targetRef:
    name: ${GATEWAY_NAME}
    group: gateway.networking.k8s.io
    kind: Gateway
