apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kamel-rest
  namespace: "${KAMEL_NS}"
  labels:
    deployment: rest-api
    service: rest-api
spec:
  parentRefs:
  - name: "$GATEWAY_NAME"
    namespace: "$GATEWAY_NS"
  hostnames:
  - "kamel-rest.${ROOT_DOMAIN_ID}"
  rules:
  - backendRefs:
    - name: rest-api
      namespace: "${KAMEL_NS}"
      port: 80
    matches:
    - method: GET
      path:
        type: PathPrefix
        value: /api/person
  - backendRefs:
    - name: rest-api
      namespace: "${KAMEL_NS}"
      port: 80
    matches:
    - method: POST
      path:
        type: Exact
        value: /api/person
  - backendRefs:
    - name: rest-api
      namespace: "${KAMEL_NS}"
      port: 80
    matches:
    - method: PUT
      path:
        type: Exact
        value: /api/person
status:
  parents: null
