---
apiVersion: v1
kind: Secret
metadata:
  name: kamel-api-key
  namespace: ${KAMEL_NS}
  labels:
    authorino.kuadrant.io/managed-by: authorino
    kuadrant.io/apikeys-by: api_key
stringData:
  api_key: secret
type: Opaque
